### ISSUE TITLE
Extension stopped working since Deneb hard fork

### ISSUE THREAD

**Issue by nflaig** [fireblocks-labs/trustless-blockchain-data-verifier#28]
The version of the LC used by the extension does not yet have the `DENEB_FORK_EPOCH` scheduled which results in error when validating the LC header is it uses the Capella fork type instead of Deneb to deserialize data received from the beacon node.

```
Error: Attested Header is not Valid Light Client Header
    at c (validateLightClientUpdate.js:13:15)
    at B (processLightClientUpdate.js:16:5)
    at c.onUpdate (index.js:15:9)
    at D.processSyncCommitteeUpdate (index.js:242:30)
    at D.sync (index.js:142:22)
    at async D.runLoop (index.js:168:17)
```

Updating `@lodestar/light-client` and `@lodestar/prover` fixes the issue.

**Comment by rdvorkin** [comment]
Fixed in 9df8b0f
